### ISSUE TITLE
Bug: Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by rix1337** [roots/issue-closer-action#4]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

issue-closer-action is using deprecated nodejs 12, which leads to a deprecation notice in github actions:
![grafik](https://user-images.githubusercontent.com/9930448/211188640-b514d210-5412-4467-81db-89791f3cb768.png)

#### What have you tried?
-

#### What insights have you gained?
in all other affected actions, an update was required

#### Possible solutions
use nodejs 16 as recommended by github

#### Temporary workarounds
-

### Steps To Reproduce

1. Use issue-closer-action
2. Check github actions log
3. See the aforementioned deprecation notice

### Expected Behavior

No deprecation notice

### Actual Behavior

Deprecation notice

### Relevant Log Output

```shell
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: roots/issue-closer@v1.1
```

### Versions

1.1

**Comment by swalkinshaw** [comment]
Fixed in https://github.com/roots/issue-closer-action/releases/tag/v1.2
